version: '3'

services:
  freecell:
    image: sebp/lighttpd
    volumes:
      - ./build:/var/www/localhost/htdocs/freecell:ro
      - ./build:/var/www/localhost/htdocs/solitaire:ro
    ports:
      - "8080:80"
    tty: true